using System;
using System.Collections.Generic;
using Jellyfin.Database.Implementations.Entities;

namespace Jellyfin.Plugin.JellyTrend.Api;

/// <summary>
/// Optional database-provider-specific query backend for the recommendation engine.
/// When registered in the Jellyfin DI container (e.g. by the PostgreSQL Database Provider
/// plugin), the recommendation engine delegates its library queries to this interface
/// instead of using <c>ILibraryManager.GetItemList</c>.
/// </summary>
/// <remarks>
/// <para>
/// Implementations receive the raw user and facet data and return only the minimal
/// projection required by <see cref="RecommendationEngine"/> — item id, TMDB provider id,
/// genre list, tag list, community rating and premiere date. This lets each provider
/// issue a single, optimised query instead of the EF Core subquery-correlated pattern
/// generated by Jellyfin''s default repository.
/// </para>
/// <para>
/// <b>Contract:</b> all methods must be safe to call from a background task thread and
/// must never throw for recoverable errors (return an empty list instead).
/// If the provider is not registered, <see cref="RecommendationEngine"/> falls back to
/// <c>ILibraryManager</c> transparently so the plugin works on SQLite without changes.
/// </para>
/// </remarks>
public interface IRecommendationQueryProvider
{
    /// <summary>
    /// Returns movies the user has played, up to <paramref name="limit"/> items.
    /// Used to build the affinity facets (genres, people, tags) for scoring.
    /// </summary>
    /// <param name="userId">The user whose play history to query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of played movies.</returns>
    IReadOnlyList<RecommendationItem> GetPlayedMovies(Guid userId, int limit);

    /// <summary>
    /// Returns movies the user has started but not finished (resume candidates).
    /// These are excluded from recommendations but included in affinity scoring.
    /// </summary>
    /// <param name="userId">The user whose resume queue to query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of in-progress movies.</returns>
    IReadOnlyList<RecommendationItem> GetResumableMovies(Guid userId, int limit);

    /// <summary>
    /// Returns unwatched movie candidates that match the given genres.
    /// </summary>
    /// <param name="userId">User whose played status is checked.</param>
    /// <param name="genres">Genres to filter by (OR logic — any match qualifies).</param>
    /// <param name="topParentIds">Library root ids to scope the query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of matching unwatched movies.</returns>
    IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByGenres(
        Guid userId,
        IReadOnlyList<string> genres,
        IReadOnlyList<Guid> topParentIds,
        int limit);

    /// <summary>
    /// Returns unwatched movie candidates associated with the given person ids
    /// (actors, directors, writers).
    /// </summary>
    /// <param name="userId">User whose played status is checked.</param>
    /// <param name="personIds">Person ids to filter by (OR logic).</param>
    /// <param name="topParentIds">Library root ids to scope the query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of matching unwatched movies.</returns>
    IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByPersons(
        Guid userId,
        IReadOnlyList<Guid> personIds,
        IReadOnlyList<Guid> topParentIds,
        int limit);

    /// <summary>
    /// Returns unwatched movie candidates that carry the given tags.
    /// </summary>
    /// <param name="userId">User whose played status is checked.</param>
    /// <param name="tags">Tags to filter by (OR logic).</param>
    /// <param name="topParentIds">Library root ids to scope the query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of matching unwatched movies.</returns>
    IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByTags(
        Guid userId,
        IReadOnlyList<string> tags,
        IReadOnlyList<Guid> topParentIds,
        int limit);

    /// <summary>
    /// Returns a random sample of unwatched movies for cold-start users
    /// (users without enough watch history to build facets).
    /// </summary>
    /// <param name="userId">User whose played status is checked.</param>
    /// <param name="topParentIds">Library root ids to scope the query.</param>
    /// <param name="limit">Maximum number of items to return.</param>
    /// <returns>Lightweight projections of random unwatched movies.</returns>
    IReadOnlyList<RecommendationItem> GetRandomUnwatchedMovies(
        Guid userId,
        IReadOnlyList<Guid> topParentIds,
        int limit);
}

/// <summary>
/// Minimal projection of a <c>BaseItem</c> used by <see cref="IRecommendationQueryProvider"/>.
/// Contains only the fields needed by <see cref="RecommendationEngine"/> for scoring.
/// </summary>
/// <param name="Id">Jellyfin item GUID.</param>
/// <param name="TmdbId">TMDB provider id, or null if not available.</param>
/// <param name="Genres">Genre names.</param>
/// <param name="Tags">Tag names.</param>
/// <param name="Studios">Studio names.</param>
/// <param name="CommunityRating">Community rating (0-10), or null.</param>
/// <param name="PremiereDate">Premiere date in UTC, or null.</param>
public sealed record RecommendationItem(
    Guid Id,
    string? TmdbId,
    IReadOnlyList<string> Genres,
    IReadOnlyList<string> Tags,
    IReadOnlyList<string> Studios,
    float? CommunityRating,
    DateTime? PremiereDate);
